### ISSUE TITLE
Verbose (-v) key not working

### ISSUE THREAD

**Issue by blackcodersec** [projectdiscovery/simplehttpserver#28]
It doesn't work when you give (-v). But, your usage support showing verbose (-v). Just simple missing :)
![Screenshot_31](https://user-images.githubusercontent.com/72689232/115121266-81d3f680-9fd3-11eb-9af6-454618fd8921.png)

And I want to know, How do I find all the logs?

**Comment by ehsandeep** [comment]
@blackcodersec you can use `simplehttpserver -h` to see all the flags.

it should be `simplehttpserver -verbose`, updated the readme.
