### ISSUE TITLE
There's no max size for the request-URI that allows remote users to send huge data.

### ISSUE THREAD

**Issue by DEMON1A** [projectdiscovery/simplehttpserver#32]
In most servers. there's a limit for the request-URI that limits the request size like: apache, nginx, python http.server. it's required to keep the server smooth and inform the user when his requests exceeds the max limit of characters and the server won't process the request it will just return an error message. processing such a requests specially when it interacts with the server increases the CPU/memory usage resulting in DDoS attacks.

The limit should be for the first request line that includes the path the user is visiting and the request method. if you gonna make any changes.

**Comment by rtcms** [comment]
@DEMON1A  This is simplehttpserver for a reason xD

**Comment by DEMON1A** [comment]
@rtcms Please don't send any replies to my issue, i don't care about what do you think and i won't explain the hall issue to you. the issue description is how all of the server **supposed** to be working. the developer is only one who can refuse or accept. but i'm saying facts.

**Comment by ehsandeep** [comment]
@DEMON1A we appreciate your suggestions for the improvements of this project, but keep in mind that we are working on a FOSS project where all input matters, so please be respectful to others.

**Comment by DEMON1A** [comment]
In fact, i didn't disrespect anyone, i talked with him with the same way he talked to me. i don't see any point of his comment instead of trolling on what i said.
