### ISSUE TITLE
How to use http/1.1 protocol

### ISSUE THREAD

**Issue by cyal1** [projectdiscovery/simplehttpserver#50]
How to use http/1.1 protocol

**Comment by Mzack9999** [comment]
@cyal1 Thanks for opening this issue. The HTTP protocol is something negotiated by the client and not enforced by the server. To force it, you should explicitly set your client to use HTTP 1.X, and, I suppose, it's also necessary to skip alpn/npn negotiation. For example, with curl, the following command performs the request with **HTTP 1.1**:

```
curl https://localhost:8000 -v --http1.1 -k
```

**Comment by cyal1** [comment]
hello, I want the service only support http/1.1
